[Core] Fix NoSuchMethodError PrintWriter(OutputStream, boolean, Charset)
The `PrintWriter(OutputStream, boolean, Charset)` method was introduced in
Java 10 and can't yet be used on Java 8. And while support for Open JDK 8 has
ended 2 months ago, Adoptium and Corretto are receiving support until 2026 and
Azul and Oracle have support until 2030.

As such we're replacing the `PrintWriter` implementation with our own
"good enough" version.

Fixes: #2575